# Generated by Django 2.0.2 on 2018-04-12 17:31

import categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='height_field',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='image_prod',
            field=models.ImageField(height_field='height_field', null=True, upload_to=categories.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='category',
            name='width_field',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
