# Generated by Django 2.0.2 on 2018-08-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20180713_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_defination',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Kategori Açıklaması'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_logo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Kategori Ismi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
