# Generated by Django 2.0.2 on 2018-08-08 14:50

import categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20180808_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_prod',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=categories.models.upload_location, width_field='width_field'),
        ),
    ]
