# Generated by Django 2.0.2 on 2018-08-11 18:33

import aktuels.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140, null=True)),
                ('explain', models.CharField(blank=True, max_length=140, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_aktuel', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=aktuels.models.upload_location, width_field='width_field')),
                ('aktuel_company_name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Aktuel Firma Ismi')),
                ('aktuel_company_site', models.CharField(blank=True, max_length=140, null=True, verbose_name='Aktuel Firma Sitesi')),
                ('image_comp', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=aktuels.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=0, null=True)),
                ('width_field', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Aktuel',
                'verbose_name_plural': 'Aktueller',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='AktuelProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('title', models.CharField(max_length=140)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exist', models.BooleanField(default=True, verbose_name='Stockta Var Mı?')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_prod', models.ImageField(height_field='height_field', null=True, upload_to=aktuels.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=0)),
                ('width_field', models.IntegerField(blank=True, default=0)),
                ('aktuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktuel_products', to='aktuels.Aktuel')),
            ],
            options={
                'verbose_name': 'Aktuel Ürünü',
                'verbose_name_plural': 'Aktuel Ürünleri',
                'ordering': ('-timestamp',),
            },
        ),
    ]
