# Generated by Django 2.0.2 on 2018-05-10 07:19

import aktuels.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aktuels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AktuelProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('title', models.CharField(max_length=140)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exist', models.BooleanField(default=True, verbose_name='Stockta Var Mı?')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_prod', models.ImageField(height_field='height_field', null=True, upload_to=aktuels.models.upload_location, width_field='width_field')),
                ('aktuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktuel_products', to='aktuels.Aktuel')),
            ],
        ),
    ]
