# Generated by Django 2.0.2 on 2018-07-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aktuels', '0002_auto_20180713_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktuel',
            name='timestamp',
        ),
    ]
