# Generated by Django 2.0.2 on 2018-07-18 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aktuels', '0003_remove_aktuel_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktuel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
