# Generated by Django 2.0.2 on 2018-05-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktuels', '0003_auto_20180510_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktuel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
