# Generated by Django 2.0.2 on 2018-08-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktuels', '0004_aktuel_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktuel',
            name='aktuel_company_name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Aktuel Firma Ismi'),
        ),
        migrations.AlterField(
            model_name='aktuel',
            name='aktuel_company_site',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Aktuel Firma Sitesi'),
        ),
        migrations.AlterField(
            model_name='aktuel',
            name='explain',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='aktuel',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aktuel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktuel',
            name='title',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='aktuel',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktuel',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
