# Generated by Django 2.0.2 on 2018-05-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktuels', '0004_aktuel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktuel',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
