# Generated by Django 2.0.2 on 2018-04-05 04:27

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('title', models.CharField(max_length=140)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exist', models.BooleanField(default=True, verbose_name='Stockta Var Mı?')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_prod', models.ImageField(height_field='height_field', null=True, upload_to=products.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=0)),
                ('width_field', models.IntegerField(blank=True, default=0)),
                ('category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='companies.Company')),
            ],
        ),
    ]
