# Generated by Django 2.0.2 on 2018-08-11 13:16

import ckeditor.fields
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180808_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ürün Özellikleri'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ürün Açıklaması'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_prod',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, verbose_name='Ürün Resmi', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Fiyat'),
        ),
    ]
