# Generated by Django 2.0.2 on 2018-08-11 13:39

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180811_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_prod',
        ),
        migrations.AddField(
            model_name='product',
            name='image_prod_first',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, verbose_name='Ürün Resmi 1', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_prod_fourth',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, verbose_name='Ürün Resmi 4', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_prod_second',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, verbose_name='Ürün Resmi 2', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_prod_third',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, verbose_name='Ürün Resmi 3', width_field='width_field'),
        ),
    ]
