# Generated by Django 2.0.2 on 2018-08-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180811_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Ürün Slug/Sayaç'),
        ),
    ]
