# Generated by Django 2.0.2 on 2018-08-11 18:32

import ckeditor.fields
import companies.models
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Marka İsmi')),
                ('brand_site', models.CharField(blank=True, max_length=140, null=True, verbose_name='Markanın Sitesi')),
                ('brand_image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=companies.models.upload_location, verbose_name='Marka Resmi', width_field='width_field')),
                ('brand_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Marka Açıklaması')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Firma İsmi')),
                ('company_site', models.CharField(blank=True, max_length=140, null=True, verbose_name='Firmanın Sitesi')),
                ('company_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Firma Açıklaması')),
                ('image_comp', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=companies.models.upload_location, verbose_name='Firma Resmi', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='companies.Company', verbose_name='Üst Kategori')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar',
                'ordering': ('-created_at',),
            },
        ),
    ]
