# Generated by Django 2.0.2 on 2018-07-12 17:29

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=140, verbose_name='Firma İsmi'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_site',
            field=models.CharField(max_length=140, verbose_name='Firmanın Sitesi'),
        ),
        migrations.AlterField(
            model_name='company',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='companies.Company', verbose_name='Üst Kategori'),
        ),
    ]
