# Generated by Django 2.0.2 on 2018-08-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20180712_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Firma İsmi')),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Firma İsmi'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_site',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Firmanın Sitesi'),
        ),
    ]
