# Generated by Django 2.0.2 on 2018-08-08 15:01

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20180808_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=companies.models.upload_location, verbose_name='Marka Resmi', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_site',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Markanın Sitesi'),
        ),
        migrations.AddField(
            model_name='brand',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brand',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Marka İsmi'),
        ),
    ]
