# Generated by Django 2.0.2 on 2018-08-11 13:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20180808_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Marka Açıklaması'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Firma Açıklaması'),
        ),
    ]
