# Generated by Django 2.0.2 on 2018-11-24 13:03

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userphoto', versatileimagefield.fields.VersatileImageField(blank=True, height_field='height_field', null=True, upload_to=accounts.models.upload_location, verbose_name='Kullanıcı Resmi', width_field='width_field')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='İsim')),
                ('surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Soyisim')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('gender', models.CharField(choices=[('E', 'Erkek'), ('K', 'Kadın')], default='E', max_length=1, verbose_name='Cinsiyet')),
                ('adress', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adres')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası')),
                ('height_field', models.PositiveIntegerField(blank=True, default=0, verbose_name='Uzunluk Değeri')),
                ('width_field', models.PositiveIntegerField(blank=True, default=0, verbose_name='Genişlik Değeri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'ordering': ('-created_at',),
            },
        ),
    ]
