# Generated by Django 2.0.2 on 2018-08-31 20:36

import accounts.models
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180812_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='height_field',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Uzunluk Değeri'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userphoto',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height_field', null=True, upload_to=accounts.models.upload_location, verbose_name='Kullanıcı Resmi', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='width_field',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Genişlik Değeri'),
        ),
    ]
