# Generated by Django 2.0.2 on 2018-11-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_Footer_Bottom_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer Alt 1. Kısım Bilgisi')),
                ('icon', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer Alt 1. Kısım İconu')),
                ('link', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer Alt 1. Kısım Linki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Footer Alt 1. Kısım Bilgisi',
                'verbose_name_plural': 'Footer Alt 1. Kısım Bilgileri',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Extra_Footer_Bottom_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer Alt 2. Kısım Bilgisi')),
                ('icon', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer Alt 2. Kısım İconu')),
                ('link', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer Alt 2. Kısım Linki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Footer Alt 2. Kısım Bilgisi',
                'verbose_name_plural': 'Footer Alt 2. Kısım Bilgileri',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Extra_Footer_Bottom_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer Alt 3. Kısım Bilgisi')),
                ('icon', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer Alt 3. Kısım İconu')),
                ('link', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer Alt 3. Kısım Linki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Footer Alt 3. Kısım Bilgisi',
                'verbose_name_plural': 'Footer Alt 3. Kısım Bilgileri',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Extra_Footer_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_head', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer İletişim Bilgisi')),
                ('icon', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer İletişim İconu')),
                ('link', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer İletişim Linki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Footer Bilgi',
                'verbose_name_plural': 'Footer Bilgileri',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Extra_Footer_Head_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer Üst 1. Kısım Bilgisi')),
                ('icon', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer Üst 1. Kısım İconu')),
                ('link', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer Üst 1. Kısım Linki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Footer Üst 1. Kısım Bilgisi',
                'verbose_name_plural': 'Footer Üst 1. Kısım Bilgileri',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Extra_Footer_Head_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer Üst 2. Kısım Bilgisi')),
                ('icon', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer Üst 2. Kısım İconu')),
                ('link', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer Üst 2. Kısım Linki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Footer Üst 2. Kısım Bilgisi',
                'verbose_name_plural': 'Footer Üst 2. Kısım Bilgileri',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Extra_Footer_Head_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer Üst 3. Kısım Bilgisi')),
                ('icon', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer Üst 3. Kısım İconu')),
                ('link', models.CharField(blank=True, max_length=280, null=True, verbose_name='Footer Üst 3. Kısım Linki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Footer Üst 3. Kısım Bilgisi',
                'verbose_name_plural': 'Footer Üst 3. Kısım Bilgileri',
                'ordering': ('-created_at',),
            },
        ),
    ]
