# Generated by Django 2.0.2 on 2018-08-12 16:39

import categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_logo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kategori Resmi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, verbose_name='Uzunluk Değeri'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_prod',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=categories.models.upload_location, verbose_name='Kategori Resmi', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='category',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, verbose_name='Genişlik Değeri'),
        ),
    ]
