# Generated by Django 2.0.2 on 2018-08-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20180812_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_logo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kategori Logo'),
        ),
    ]
