# Generated by Django 2.0.2 on 2018-08-31 20:36

import categories.models
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20180812_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='height_field',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Uzunluk Değeri'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_prod',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height_field', null=True, upload_to=categories.models.upload_location, verbose_name='Kategori Resmi', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='category',
            name='width_field',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Genişlik Değeri'),
        ),
    ]
