# Generated by Django 2.0.2 on 2018-08-11 18:33

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('E', 'Erkek'), ('K', 'Kadın')], default='E', max_length=1)),
                ('userphoto', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=accounts.models.upload_location, verbose_name='Kullanıcı Resmi', width_field='width_field')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='İsim')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Soyisim')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('adress', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('height_field', models.IntegerField(blank=True, default=0)),
                ('width_field', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'ordering': ('-created_at',),
            },
        ),
    ]
