# Generated by Django 2.0.2 on 2018-08-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='adress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('E', 'Erkek'), ('K', 'Kadın')], default='E', max_length=1, verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, verbose_name='Uzunluk Değeri'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Soyisim'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, verbose_name='Genişlik Değeri'),
        ),
    ]
