# Generated by Django 2.0.2 on 2018-07-24 15:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_userphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height_field',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='width_field',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userphoto',
            field=models.ImageField(height_field='height_field', null=True, upload_to=accounts.models.upload_location, verbose_name='Kullanıcı Resmi', width_field='width_field'),
        ),
    ]
