# Generated by Django 2.0.2 on 2018-07-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180724_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('E', 'Erkek'), ('K', 'Kadın')], default='E', max_length=1),
        ),
    ]
