# Generated by Django 2.0.2 on 2018-09-06 20:29

import aktuels.models
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Aktuel Slug')),
                ('title', models.CharField(blank=True, max_length=140, null=True, verbose_name='Aktuel Başlığı')),
                ('explain', models.CharField(blank=True, max_length=140, null=True, verbose_name='Aktuel Açıklaması')),
                ('aktuel_company_name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Aktuel Firma Ismi')),
                ('aktuel_company_site', models.CharField(blank=True, max_length=140, null=True, verbose_name='Aktuel Firma Sitesi')),
                ('image_aktuel', versatileimagefield.fields.VersatileImageField(blank=True, height_field='height_field', null=True, upload_to=aktuels.models.upload_location, verbose_name='Aktuel Firma Resmi', width_field='width_field')),
                ('image_aktuel_comp', versatileimagefield.fields.VersatileImageField(blank=True, height_field='height_field', null=True, upload_to=aktuels.models.upload_location, verbose_name='Aktuel Resmi', width_field='width_field')),
                ('height_field', models.PositiveIntegerField(blank=True, default=0, verbose_name='Uzunluk Değeri')),
                ('width_field', models.PositiveIntegerField(blank=True, default=0, verbose_name='Genişlik Değeri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Aktuel',
                'verbose_name_plural': 'Aktueller',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AktuelProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('title', models.CharField(max_length=140)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exist', models.BooleanField(default=True, verbose_name='Stockta Var Mı?')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_aktuel_prod', versatileimagefield.fields.VersatileImageField(height_field='height_field', null=True, upload_to=aktuels.models.upload_location, width_field='width_field')),
                ('height_field', models.PositiveIntegerField(blank=True, default=0)),
                ('width_field', models.PositiveIntegerField(blank=True, default=0)),
                ('aktuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktuel_products', to='aktuels.Aktuel')),
            ],
            options={
                'verbose_name': 'Aktuel Ürünü',
                'verbose_name_plural': 'Aktuel Ürünleri',
                'ordering': ('-timestamp',),
            },
        ),
    ]
