# Generated by Django 2.0.2 on 2018-09-10 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aktuels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AktuelSlug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140, null=True, verbose_name='Aktuel Başlığı')),
                ('explain', models.CharField(blank=True, max_length=140, null=True, verbose_name='Aktuel Açıklaması')),
                ('aktuel_company_name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Aktuel Firma Ismi')),
                ('aktuel_company_site', models.CharField(blank=True, max_length=140, null=True, verbose_name='Aktuel Firma Sitesi')),
            ],
        ),
        migrations.RemoveField(
            model_name='aktuel',
            name='aktuel_company_name',
        ),
        migrations.RemoveField(
            model_name='aktuel',
            name='aktuel_company_site',
        ),
        migrations.RemoveField(
            model_name='aktuel',
            name='explain',
        ),
        migrations.RemoveField(
            model_name='aktuel',
            name='title',
        ),
        migrations.AlterField(
            model_name='aktuel',
            name='slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktuelslug', to='aktuels.AktuelSlug', verbose_name='Aktuel Slug'),
        ),
    ]
