# Generated by Django 2.0.2 on 2018-08-12 16:39

import aktuels.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aktuels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aktuel',
            options={'ordering': ('-created_at',), 'verbose_name': 'Aktuel', 'verbose_name_plural': 'Aktueller'},
        ),
        migrations.RemoveField(
            model_name='aktuel',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='aktuel',
            name='updated',
        ),
        migrations.AddField(
            model_name='aktuel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aktuel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='aktuel',
            name='explain',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Aktuel Açıklaması'),
        ),
        migrations.AlterField(
            model_name='aktuel',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, verbose_name='Uzunluk Değeri'),
        ),
        migrations.AlterField(
            model_name='aktuel',
            name='image_aktuel',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=aktuels.models.upload_location, verbose_name='Aktuel Firma Resmi', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='aktuel',
            name='image_comp',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=aktuels.models.upload_location, verbose_name='Aktuel Resmi', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='aktuel',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Aktuel Slug'),
        ),
        migrations.AlterField(
            model_name='aktuel',
            name='title',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Aktuel Başlığı'),
        ),
        migrations.AlterField(
            model_name='aktuel',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, verbose_name='Genişlik Değeri'),
        ),
    ]
