# Generated by Django 2.0.2 on 2018-09-11 11:40

import aktuels.models
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aktuels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktuel',
            name='aktuel_images',
        ),
        migrations.AddField(
            model_name='aktuelproducts',
            name='aktuel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aktuel_products', to='aktuels.Aktuel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aktuelproducts',
            name='image_aktuel_prod',
            field=versatileimagefield.fields.VersatileImageField(height_field='height_field', null=True, upload_to=aktuels.models.upload_location, verbose_name='Aktuel Ürün Resmi', width_field='width_field'),
        ),
    ]
