# Generated by Django 2.0.2 on 2018-09-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktuels', '0002_auto_20180911_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktuelproducts',
            name='explain',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Açıklama'),
        ),
    ]
