# Generated by Django 2.0.2 on 2018-09-01 12:09

from django.db import migrations
import tickets.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20180831_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcompany',
            name='image_comp',
        ),
        migrations.AddField(
            model_name='ticketcompany',
            name='image_ticket_comp',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height_field', null=True, upload_to=tickets.models.upload_location, verbose_name='Ticket Firmasının Resmi', width_field='width_field'),
        ),
    ]
