# Generated by Django 2.0.2 on 2018-09-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20180901_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcompany',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Ticket Slug'),
        ),
    ]
