# Generated by Django 2.0.2 on 2018-09-01 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketcompany_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='company',
        ),
        migrations.AddField(
            model_name='ticketcompany',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='tickets.Ticket', verbose_name='Ticket'),
        ),
    ]
