# Generated by Django 2.2 on 2019-06-02 17:17

from django.db import migrations, models
import products.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_field',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Uzunluk Değeri'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_prod_first',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, verbose_name='Ürün Resmi 1', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_prod_fourth',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, verbose_name='Ürün Resmi 4', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_prod_second',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, verbose_name='Ürün Resmi 2', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_prod_third',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, verbose_name='Ürün Resmi 3', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_field',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Genişlik Değeri'),
        ),
        migrations.DeleteModel(
            name='ProductInfo',
        ),
    ]
