# Generated by Django 2.0.2 on 2018-12-12 18:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
import products.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=140, null=True, verbose_name='Ürün Slug / Sayacı')),
                ('image_prod_first', versatileimagefield.fields.VersatileImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, verbose_name='Ürün Resmi 1', width_field='width_field')),
                ('image_prod_second', versatileimagefield.fields.VersatileImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, verbose_name='Ürün Resmi 2', width_field='width_field')),
                ('image_prod_third', versatileimagefield.fields.VersatileImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, verbose_name='Ürün Resmi 3', width_field='width_field')),
                ('image_prod_fourth', versatileimagefield.fields.VersatileImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, verbose_name='Ürün Resmi 4', width_field='width_field')),
                ('height_field', models.PositiveIntegerField(blank=True, default=0, verbose_name='Uzunluk Değeri')),
                ('width_field', models.PositiveIntegerField(blank=True, default=0, verbose_name='Genişlik Değeri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Ürün Bilgisi',
                'verbose_name_plural': 'Ürün Bilgileri',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='exist',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_prod_first',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_prod_fourth',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_prod_second',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_prod_third',
        ),
        migrations.RemoveField(
            model_name='product',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width_field',
        ),
        migrations.AddField(
            model_name='product',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ürün Bedeni'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='companies.Brand', verbose_name='Marka'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ürün Rengi'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='number',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ürün Numarası'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Eski Ürün Fiyatı'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ürün Boyutu'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ürün Ağırlığı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name='Kategori'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='companies.Company', verbose_name='Firma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ürün Fiyatı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='productinfo', to='products.ProductInfo', verbose_name='Ürün Slug / Sayacı'),
            preserve_default=False,
        ),
    ]
