# Generated by Django 2.0.2 on 2018-08-26 14:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180826_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AddField(
            model_name='product',
            name='feature',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ürün Özellikleri'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ürün Açıklaması'),
        ),
        migrations.DeleteModel(
            name='ProductContent',
        ),
]