# Generated by Django 2.0.2 on 2018-08-31 19:32

from django.db import migrations
import products.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180826_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='image_prod_first',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, verbose_name='Ürün Resmi 1', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='image_prod_fourth',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, verbose_name='Ürün Resmi 4', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='image_prod_second',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, verbose_name='Ürün Resmi 2', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='image_prod_third',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, verbose_name='Ürün Resmi 3', width_field='width_field'),
        ),
]