# Generated by Django 2.0.2 on 2018-12-12 16:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180831_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=datetime.datetime(2018, 12, 12, 16, 46, 49, 460858, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='companies.Brand', verbose_name='Marka'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name='Kategori'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='companies.Company', verbose_name='Firma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='productinfo', to='products.ProductInfo', verbose_name='Ürün Slug / Sayacı'),
            preserve_default=False,
        ),
    ]
